name: NasyMoe
version: 0.1.2.0

synopsis: Personal website of Nasy.
description: Personal website of Nasy.
author: Nasy
maintainer: nasyxx+nasymoe@gmail.com
category: Web

ghc-options:
  - -Wall -Werror

dependencies:
  - Cabal

executables:
  site:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base
      - filepath
      - hakyll
      - process
      - text
