#+TITLE: 洒水啦！
#+DATE: <2018-06-07 Thu>
#+AUTHOR: Nasy
#+TAGS: 花, flower, hana, 随笔, essay
#+CATEGORIES: Flower, Eassy
#+SUMMARY: 当你的电脑被别人洒水后，你会怎么做呢？
#+HREF: sprinkle-water

本来这件事是发生在4月初的，没想到，直到今天，事情才终于告一段落。

* 事件大致经过

那是4月初的某个早晨，大约7点半，我迷迷糊糊的醒了过来。当然，醒过来，肯定是因为发生了很多噪音啦！具体就是，舍友 L 去饮水机接水，然后哗啦啦几声过后，就听到他抱怨一句“好烦”，然后抽了几张纸擦了擦。最后，我又睡了过去。

接下来是风平浪静的一天。什么也没发生。我呢，继续改着我的毕业论文，延毕的舍友 Z，也继续享受着通宵达旦游戏之后的美梦。就这样过去了一天。

在洒水事件后的第三天，我发现舍友 Z 竟然没在打游戏，很是疑惑，随口问了句：

“Z，你怎么没打游戏呢？”

“我电脑好像进水了烧了，我打开的时候，键盘上都是水。”

...

交谈后，我明白了，舍友 L 似乎想蒙混过关？虽然不知道他是怎么想的，这个思想是及其不端正啊喂！就算其他人睡着了，毕竟我是亲眼看到你洒了水的，怎么能不跟同一个宿舍的人说呢？后来 L 回到宿舍后，也承认自己洒水了，虽然依然找了借口“我把盖子上的水擦干了”。

尽管，我友善地提醒了一下，进水这种事情，修的越早越好，L 并没有立刻去帮 Z 修电脑。拖了大概两周，才去修。（这里要说一下，Z 是台湾人，而且脾气超好的！啊，虽然 L 也是台湾人，不过脾气还挺暴躁的。）修理的人表示，你这进水时间很长了吧，你看，这些全都腐蚀了，基本上不可能修只能换了。最终的维修费用，加上换的部件费用总共 4000 元。

* 后续

本以为，那个时候，修好后就结束了。不过，事情没有那么简单呢。昨天晚上，Z 带着几个同班同学来找 L 要钱了。

Z 这两三周以来，每两三天都会在晚上跟我吃一次，虽然是刷我的卡，不过，我也不太在乎，食堂不算太贵，他的卡充值又很麻烦，而且他人挺好的w. 除了跟我吃，另外的时间，是跟另外一个同学 F 吃（F 来自澳门。）昨天，了解 Z 没钱的 F 看不下去了，表示，你一个宿舍不好开口的话，我帮你要吧。

...

然后，就出现了昨晚要钱的那一幕。

...（睡迷糊中）

F: “L 你是不是差着 Z 修电脑的钱没还啊？”

L: “我还了啊！”

F: “你把差着的 2400 快还他。他没钱吃饭了。”

L: “我没钱！”

嗯...L 作为一个 Dota2 玩家，我亲眼看着他前几天买了 20 个以上的宝瓶（每个 12 元）。当然，就更不用说，他每天吃外卖，吃夜宵了。而且，舍友 H 表示，L 修电脑的隔天就跟他妈妈要了 4000 来作为修电脑的费用。

F: “跟你妈妈要啊！”

我: “都过了这么长时间了，不可能没机会要吧！”

又磨蹭了几句，L 转了 *2000* 给 Z。

F: “还有 400，赶紧转啊。”

L: “我不想转！转给他，也是你们带着他去上网。”

F/我: “他上网，用他自己的钱，关你什么事？”

L: “你们别来烦我，我烦的很。”

这时，又有一个同学走了进来，是平常就和 Z 一起打游戏的 L2。

L2: “怎么了，怎么这么吵？”

F: “L 欠 Z 钱，不想还。”

L2: “还有这种事？”，面向 L “还他啊！欠人钱还有不还的说法喽。”

L: “我还给他，也是你们带着他去上网！你们答应我，不带他去上网，就还。”

..: “你是他妈妈还是爸爸吗？”

...（若干磨蹭）

L: “我转了，你们别来烦我了，我今天很烦。”

F/L2: “还有这种人？”

L: “你们赶紧从宿舍出去，不欢迎你们。”

我: “啊，再来玩，我是舍长，我欢迎你们啊。” （这种时候，我还真喜欢对着干，毕竟我要走了w）

* 与 Z 的闲聊

“我还挺好奇，他怎么没还你钱？你没跟他要吗？”

“要了啊，要了那么多次，他一直说没钱，我也没什么办法。”

“他没钱不跟他家里要吗？”

“要了的，听 H 说过，他隔天就跟他妈要了 4000 了。而且你看看他的生活方式，像是没钱的么？”

“昨天，怎么会突然 F 来要钱的？”

“F 说，他看不下去了。”

“你没钱了，没跟你妈妈要一点吗？没跟你妈妈说他没还钱吗？”

“跟我妈说，她肯定会说算了，搞好同学关系。她会在乎这 4000 吗？”

* 感想

当我的电脑被人洒水，弄坏的时候，我会怎么处理呢？

** 发生的时间

就个人看来，首先是分时期吧。

*** 紧急时刻

如果是 Z 的那个时候，两三天后就答辩了，被洒了水。我啊，肯定会非常生气呢。肯定不会像 Z 那样，友善，毕竟 Z 还不用答辩，我要答辩了啊。这个害我电脑坏了，资料丢了，错过了答辩，大概是要延期毕业了吧？特别是 Mac，那些 SSD 都是在主板上的吧，主板烧了，苹果又不修，只换，这些东西就一起换掉了。虽然这些重要资料大都多处备份，但是突然生产力工具没了，能不生气吗？不过应该还是会很冷静的。

*** 非紧急时刻

非紧急时刻，大概不会怎样，最多是叹几声气，哀悼一下我那可怜的 Mac...

** 对方的态度

态度决定一切。

首先是，洒上去后的应急处理。不说每个人遇到洒水的时候都会抢救，但是，最起码要第一时间通知我，让我明白是谁做的。这一点很重要，对于我来说，这关系到我是否会让洒水那家伙负担全额的维修费用。洒水事件是意外，是一个事故，肯定不会有人是故意做的，真诚的告诉我的话，说不定就不要你出钱修理了呢？毕竟电脑老旧了，也有心想换新电脑了。当然，像 L 这样的，不用说，我不仅会让他出全额的，还要让他负责各种乱七八糟的费用（比如，莫名其妙延毕的话，不帮我出新的一年的学费吗？）。

其次是付钱的态度。因为并不是每个同学都那么富有，一下子拿出好几千，所以，只要在约定时间内还清，我都能接受。不过像 L 这样，敢说不还？啧啧...

最后嘛，还有平时的评价。平常很烦人的话，要求会比其他人严格很多呢。

#+HTML: <hr/>

人无完人，我想，当我不小心洒水到别人电脑上的话，我肯定是会第一时间应急处理，以及告知那家伙的。当然最后怎么修，看那家伙啦。

以上，祝愿大家都不会洒水或者被洒水w
